---
esphome:
  name: doorbell
  platform: ESP8266
  board: esp01_1m
# on_boot:
#  priority: 800.0
#    then:
#      - output.turn_on: relay

# WiFi connection, correct these
# with values for your WiFi.
wifi:
  ssid: !secret ssid_iot
  password: !secret password_iot
  domain: !secret domain

    # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: !secret fallback_password

# Enable logging.
logger:

# Enable Home Assistant API.
api:

# Enable over-the-air updates.
ota:

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Doorbell ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Doorbell IP
    ssid:
      name: Doorbell SSID
    bssid:
      name: Doorbell BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Doorbell Uptime
    id: uptime_sensor
    on_value_range:
      above: 1000000
      then:
        - switch.turn_on: restart_bell

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Doorbell WiFi Signal
    update_interval: 60s

# Exposed switches.
switch:
  # Switch to restart the doorbell.
  - platform: restart
    name: Doorbell Restart
    id: restart_bell

output:
  # Switch to turn on/off the chime.
  - platform: gpio
    id: relay
    inverted: true
    pin:
      number: GPIO0
      mode: OUTPUT

# Binary sensor representing the
# Doorbell button push.
binary_sensor:
  # Binary Input to turn on/off chime when
  # doorbell button is pushed.
  #
  # It creates a "virtual" switch based
  # on a home assistant state variable.
  - platform: homeassistant
    name: "Nap mode input from home assistant"
    id: nap_mode
    entity_id: input_boolean.nap_mode

  - platform: homeassistant
    name: "Quite mode input from home assistant"
    id: quite_mode
    entity_id: input_boolean.quite_mode

  - platform: gpio
    id: button
    name: Doorbell Button
    pin:
      # Connected to GPIO on the ESP-01S.
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      # Small filter, to debounce the button press.
      - delayed_on_off: 10ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            and:
              - binary_sensor.is_off: nap_mode
              - binary_sensor.is_off: quite_mode
              - sensor.in_range:
                  id: uptime_sensor
                  above: 3
          then:
            - output.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - output.turn_off: relay
      # Debouce the automation
      - delay: 2s