esphome:
  name: iot-bt
  friendly_name: IOT BT Proxy

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret iot_bt_key

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

ota:
  password: !secret ota_password
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret isolated_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "IOT BT Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

sensor:
  - platform: uptime
    name: Uptime