esphome:
  name: master-white-noise
  friendly_name: master-white-noise

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret main_bed_api_key

ota:

wifi:
  domain: !secret domain
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master Noise Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Toggle Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Master White Noise Status"

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    name: "Master White Noise"
    icon: "mdi:volume-high"
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    id: status_led
    pin: GPIO13
    restore_mode: ALWAYS_OFF
    inverted: yes
