# Basic Config
esphome:
  name: "modem-reset"
  platform: ESP8266
  board: esp01_1m

wifi:
  domain: !secret domain
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "General Switch Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

logger:
  #baud_rate: 0 # (UART logging interferes with cse7766)

api:
  encryption:
    key: !secret modem_reset_api_key

ota:

# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S31 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    name: "Switch"
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: led_status
    pin: GPIO13
    restore_mode: ALWAYS_OFF
    inverted: yes
