esphome:
  name: nursery-fan
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
api:
ota:

wifi:
  domain: !secret domain
  ssid: !secret ssid_iot
  password: !secret password_iot

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nursery Fan Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
     number: GPIO0
     mode: INPUT_PULLUP
     inverted: True
    name: "Toggle Button"
    on_press:
     - switch.toggle: relay
  - platform: status
    name: "Nursery Fan Status"

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    name: "Nursery Fan"
    icon: "mdi:fan"
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    id: status_led
    pin: GPIO13
    restore_mode: ALWAYS_OFF
    inverted: yes

#status_led:
#  pin: GPIO13