---
substitutions:
  id_prefix: ratgdov25
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3
  name: ratgarage-6ee702
  friendly_name: ratgarage

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ratgdo.esphome
    version: "2.5"

esp8266:
  board: d1_mini_lite
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

ota:

api:
  id: api_server
  encryption:
    key: !secret ratgdo_api_key

wifi:
  domain: !secret domain
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "ratgdo Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

logger:
