esphome:
  name: salt-sensor
  friendly_name: salt-sensor

esp32:
  board: m5stack-atom

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret salt_sensor_api_key

ota:
  password: !secret ota_password
  platform: esphome

wifi:
  domain: !secret domain
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Salt-Sensor Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Exposed switches.
button:
  # Switch to restart the esp.
  - platform: restart
    name: Restart

# Example configuration entry
sensor:
  - platform: uptime
    name: Uptime
  - platform: hx711
    name: "Weight"
    dout_pin: GPIO32
    clk_pin: GPIO26
    update_interval: 60s
    unit_of_measurement: kg
    device_class: weight
    state_class: measurement
    accuracy_decimals: 1
    filters:
      # Reminder, these are done in the order
      # that they are defined.
      - calibrate_linear:
          - 524742 -> 0
          - 575643 -> 2.27
          - 1019369 -> 20.32
          - 1522059 -> 40.32
          - 2515949 -> 79.38
      # - offset: -17
      - clamp:
          max_value: 100
          min_value: -10
          ignore_out_of_range: true
