substitutions:
  name: tagreader-8bfa06
packages:
  adonno.tag_reader: github://adonno/tagreader/tagreader.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret tagreader_8bfa06_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
