# Basic Config
esphome:
  name: washing_machine
  platform: ESP8266
  board: esp01_1m

wifi:
  domain: !secret domain
  ssid: !secret ssid_iot
  password: !secret password_iot

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Washing Machine Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
api:
ota:

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S31 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    update_interval: 5s
    current:
      name: "Current"
      accuracy_decimals: 1
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
    power:
      name: "Power"
      accuracy_decimals: 1
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin: GPIO13